{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_GetFirstData", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_GetLastData", "rerun": "0"}}, "suite_name": "test_Get_LocalData.py"}, "1": {"suite_name": "test_get_data_workbook.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_load1", "rerun": "0"}, "1": {"status": "FAIL", "message": "       AssertionError: assert 'There was a ...y again soon.' == 'The username...nd try again.'\n         - The username you entered doesn't belong to an account. Please check your username and try again.\n         + There was a problem logging you into Instagram. Please try again soon.\n", "test_name": "test_load2", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}}, "2": {"suite_name": "test_write_workbook.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_write1", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_write2", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_write3", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_write4", "rerun": "0"}}, "status": {"total_pass": 4, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}}}, "date": "October 31, 2022", "start_time": 1667199011.824777, "total_suite": 3, "status": "FAIL", "status_list": {"pass": "7", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}